### ISSUE TITLE
FRONTEND: login page

### ISSUE THREAD

**Issue by nahir1009** [SharkCoders/FinalProject2023#2]
voy a hacer el html y css de login y register page.
[https://github.com/orgs/SharkCoders/projects/1/views/1?pane=issue&itemId=37455939](url)

**Comment by IvetteJN** [comment]
Historia de usuario: el formulario de login necesita un formulario para registro de nuevo usuario.

**Comment by Leopladom** [comment]
Historia de usuario #2: 
1) se observa un leve desplazamiento del texto dentro del input de los campos contraseña y usuario (al rellenar con texto, el mismo se acerca mucho al titulo del campo).
2) al tratarse de un emprendimiento que vende libros, a mi forma de ver no debería ser tan marcado el efecto Hover en el botón "ingresar" y en el botón "registrarse" tan poco , quizás algo mas discreto en ambos lo podría hacer mas amigable a la vista.

**Comment by nahir1009** [comment]
cambios finales agregado
