### ISSUE TITLE
Buscar y recabar info e imágenes sobre el producto a comercializar.

### ISSUE THREAD

**Issue by Leopladom** [SharkCoders/FinalProject2023#24]
![48 leyes](https://github.com/SharkCoders/FinalProject2023/assets/114880850/7c45ad17-55be-43ab-a353-6b8e152a3b4c)
![cod penal](https://github.com/SharkCoders/FinalProject2023/assets/114880850/5321a266-2240-47a7-8cc1-f8b94bd460d4)
![cod procesal](https://github.com/SharkCoders/FinalProject2023/assets/114880850/7e7327b7-4eea-4e36-bea8-ee407147c9c3)
![Codigo CyC](https://github.com/SharkCoders/FinalProject2023/assets/114880850/d8ecc19d-1c58-4196-9191-1e2d76b2083e)
![const nacional](https://github.com/SharkCoders/FinalProject2023/assets/114880850/7214edea-5ec6-450c-ab2b-1c90ba6c8c55)
![los 7 habitos](https://github.com/SharkCoders/FinalProject2023/assets/114880850/5f5746fa-cd05-4603-9d61-b1e11f807db9)
![padre rico padre pobre](https://github.com/SharkCoders/FinalProject2023/assets/114880850/6569166d-fb1c-4ffd-b613-130b700f481e)
![php](https://github.com/SharkCoders/FinalProject2023/assets/114880850/b391e3b1-71fe-4590-aca2-b674b965f414)
![piense y hagase rico](https://github.com/SharkCoders/FinalProject2023/assets/114880850/7a36a98e-b44b-4370-93e2-19048bbaefed)
![trilogia esdla](https://github.com/SharkCoders/FinalProject2023/assets/114880850/795e32a4-8880-42a4-a505-c3798f10d5e3)
![edgar al poe](https://github.com/SharkCoders/FinalProject2023/assets/114880850/cbb7bfe2-3884-40fc-a671-6b9ec9f1aaa9)
![hp](https://github.com/SharkCoders/FinalProject2023/assets/114880850/8c11c219-15d8-43d5-af4c-70fd1490f081)
[descripciones.docx](https://github.com/SharkCoders/FinalProject2023/files/12519046/descripciones.docx)

**Comment by Leopladom** [comment]
imágenes re dimensionadas para que todas tengan el mismo tamaño y no causen defectos visuales
![48 leyes](https://github.com/SharkCoders/FinalProject2023/assets/114880850/04d584d1-ef43-419b-8033-2a8f835c7b4c)
![cod penal](https://github.com/SharkCoders/FinalProject2023/assets/114880850/fabf527c-7e91-4dac-be6a-f28d945d283c)
![cod procesal](https://github.com/SharkCoders/FinalProject2023/assets/114880850/0eeaf984-8e21-44a0-91b4-c4a97a1cab73)
![Codigo CyC](https://github.com/SharkCoders/FinalProject2023/assets/114880850/d5793216-6024-4ec4-969b-e1ab7cba7dc8)
![const nacional](https://github.com/SharkCoders/FinalProject2023/assets/114880850/6f3662d0-225d-42af-8fef-07dbacbd9009)
![edgar al poe](https://github.com/SharkCoders/FinalProject2023/assets/114880850/5c72abe3-48f0-405d-a8af-056e54b93898)
![hp](https://github.com/SharkCoders/FinalProject2023/assets/114880850/fdd44ee1-d7c7-4c34-9bf8-4dca2b750287)
![los 7 habitos](https://github.com/SharkCoders/FinalProject2023/assets/114880850/a60719b5-42d5-406d-aee1-ec5aa1a65a2d)
![padre rico padre pobre](https://github.com/SharkCoders/FinalProject2023/assets/114880850/095e5bb2-79c1-4aa8-924f-70425ee9941b)
![php](https://github.com/SharkCoders/FinalProject2023/assets/114880850/8da0cc26-f0c6-4464-a71e-fac42d5e4dbf)
![piense y hagase rico](https://github.com/SharkCoders/FinalProject2023/assets/114880850/00748bd2-fad6-4787-a22c-21207011636b)
![trilogia esdla](https://github.com/SharkCoders/FinalProject2023/assets/114880850/027bbcbc-5c6e-429d-b745-cc2f0c66c68c)

**Comment by Leopladom** [comment]
finalizadas las revisiones

**Comment by IvetteJN** [comment]
https://github.com/orgs/SharkCoders/projects/1/views/1?pane=issue&itemId=39119502
