### ISSUE TITLE
FRONTEND: JS, filtro de búsqueda por categoría de libro

### ISSUE THREAD

**Issue by IvetteJN** [SharkCoders/FinalProject2023#36]
https://github.com/orgs/SharkCoders/projects/1/views/1?pane=issue&itemId=39122415

**Comment by IvetteJN** [comment]
Historia de usuario #6: como usuario, en la landing page en la sección que te dirige a la página de productos, colocaría un filtro de búsqueda de libros por categoría.

**Comment by nahir1009** [comment]
dejo mis correcciones :
1- mejorar la incorporación de los botones con imágenes .
2- el script actual filtra filtra un array y los muestra en la consola ,lo que debe hacer es al clickear la imagen redirigirte al html productos y mostarte dicha categoría seleccionada (filtrar)
3- acá aparece un archivo js y un script dentro del HTML, debes borrar uno (es mejor hacerlo en un archivo js aparte).

**Comment by nahir1009** [comment]
dejo mis correciones: podes usar la propiedad  location. href en javascript para ir a otra pagina html y para el filtro usar un array con una funcion forEach.
Espero te sirva esa informacion

**Comment by IvetteJN** [comment]
Este issue continuará su desarrollo en el sprint 2 del proyecto.

**Comment by AnaliaPellicer** [comment]
Se logró terminar el filtro y agregar los botones de cada categoria.
