### ISSUE TITLE
BACKEND: ABSTRACCIÓN. se debe crear el Diagrama de Clases (modelo de objetos). Pueden usar como herramienta también https://app.diagrams.net/

### ISSUE THREAD

**Issue by IvetteJN** [SharkCoders/FinalProject2023#53]
https://github.com/orgs/SharkCoders/projects/1/views/1?pane=issue&itemId=39121557

**Comment by AnaliaPellicer** [comment]
[diagrama de clases.drawio.pdf](https://github.com/SharkCoders/FinalProject2023/files/12664696/diagrama.de.clases.drawio.pdf)

https://drive.google.com/file/d/1uuMUekfNja-tJHRP_tTNNBoFPEM8RGb7/view?usp=sharing

Dejo el PDF con el diagrama para ser revisado y link de drive para realizar modificaciones si les parece necesario.

**Comment by nahir1009** [comment]
el stock cambiaria el tipo de dato de boolean a numerico o entero  y faltarian las clases usuario_cliente/comun y usuario_admin que serian hijos de usuario

**Comment by AnaliaPellicer** [comment]
Dejo nuevo diagrama con correciones segun sujerencias de nahir1009. 
[Diagrama de clases .drawio.pdf](https://github.com/SharkCoders/FinalProject2023/files/12673162/Diagrama.de.clases.drawio.pdf)
