### ISSUE TITLE
FRONTEND: Landing page

### ISSUE THREAD

**Issue by AnaliaPellicer** [SharkCoders/FinalProject2023#7]
Con la finalidad de generar futuras oportunidades de venta de los productos dispoibles, se recopila datos personales y preferencias de compra.

**Comment by IvetteJN** [comment]
[https://github.com/orgs/SharkCoders/projects/1/views/1?pane=issue&itemId=37027405](url)

**Comment by nahir1009** [comment]
1- Falta agregar un h1 al html y quizás un Main.
2- cambiar el tamaño del texto categoría es muy pequeño (quizás renplazar el p por un h3)
3- centrar mejor cada sección
