### ISSUE TITLE
SPRINT 2: Frontend. Página de producto.

### ISSUE THREAD

**Issue by IvetteJN** [SharkCoders/FinalProject2023#75]
Producción del sitio web de la tienda navegable con estructura HTML, semántica, estilos CSS y Bootstrap (No es plantilla mockup, ni imagen). Páginas web requeridas como mínimo: landing page, quienes somos, contacto, galería de productos con posibilidad de acceder a la descripción de cada producto o servicio.
En nuestro primer sprint cubrimos todo este desarrollo. Queda desarrollar la página "oculta" de resumen del libro. 

Valoración: Pasa las validaciones de html y css de la W3C. Links: https://validator.w3.org/ y https://jigsaw.w3.org/css-validator/

**Comment by Leopladom** [comment]
tarea finalizada
