### ISSUE TITLE
SPRINT 2: Frontend. Login page.

### ISSUE THREAD

**Issue by IvetteJN** [SharkCoders/FinalProject2023#76]
Formularios login y registro con sus respectivas validaciones y mensajes personalizados al usuario. Ej. validar por tipos de inputs (text, number, email, date, select, segun lo que se requiera), agregar maxlenght y minlenght en los campos nombres, apellido, si solicitan DNI, usar MIN=1000000 MAX=99999999, por ejemplo.

En este segundo sprint, corresponde realizar las validaciones.

Valoración: Logra crear los formularios de login y registro con sus respectivas validaciones y mensajes personalizados al usuario. Pasa las validaciones de html y css de la W3C. Links: https://validator.w3.org/ y https://jigsaw.w3.org/css-validator/

**Comment by 1pame** [comment]
Se realizo con éxito la inserción de validaciones del formulario de login
