### ISSUE TITLE
Nombre - Logo - Favicon

### ISSUE THREAD

**Issue by Leopladom** [SharkCoders/FinalProject2023#8]
en proceso, en primera instancia se crearon varias opciones y se sometió a votación el logo a usar. ya con la opción elegida, se comienza proceso de creación.

**Comment by Leopladom** [comment]
![2](https://github.com/SharkCoders/FinalProject2023/assets/114880850/640f9737-4760-4595-a090-950a8ad69bbf)

![favi](https://github.com/SharkCod
![m](https://github.com/SharkCoders/FinalProject2023/assets/114880850/6cd66f3a-b577-46fc-9b3b-fe8b919e5258)
ers/FinalProject2023/assets/114880850/83bdfb2d-fea3-434e-9844-d85a672df0f2)

**Comment by Leopladom** [comment]
Actualizacion u opcion2
![3](https://github.com/SharkCoders/FinalProject2023/assets/114880850/f45dfa13-9864-4b33-a169-d321af1c95b3)
![4](https://github.com/SharkCoders/FinalProject2023/assets/114880850/1a7bfbfe-a553-4c9f-b46a-bd828ffe6969)
![1](https://github.com/SharkCoders/FinalProject2023/assets/114880850/d6d7cdb3-4f68-442c-b03a-fc6420142530)
![2](https://github.com/SharkCoders/FinalProject2023/assets/114880850/a848b21a-b142-45fa-aeab-fcb73c33a44a)

**Comment by IvetteJN** [comment]
https://github.com/orgs/SharkCoders/projects/1/views/1?pane=issue&itemId=37242733
